In [1]:
import pandas as pd
from pandas.io.json import json_normalize

### Reading Data From Binance
ðŸ”— Source: https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-data

Getting M5 and M1 to DataFrame

In [2]:
url_binance_bnbusdt_5m = "https://api.binance.com/api/v3/klines?symbol=BNBUSDT&limit=1000&interval=5m"
df_binance_bnbusdt_5m = pd.read_json(url_binance_bnbusdt_5m)

df_binance_bnbusdt_5m.columns = [
    'open_time', 
    'open_price', 
    'high_price', 
    'low_price', 
    'close_price', 
    'volume', 
    'close_time', 
    'quote_asset_volume', 
    'number_of_trades', 
    'taker_buy_base_asset_volume', 
    'taker_buy_quote_asset_volume', 
    'unused'
]

df_binance_bnbusdt_5m

,open_time,open_price,high_price,low_price,close_price,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,unused
0,1665141900000,284.5,284.5,284.3,284.4,371.447,1665142199999,105625.3143,318,173.538,49356.9103,0
1,1665142200000,284.3,284.5,284.3,284.5,569.677,1665142499999,162046.5800,549,507.688,144422.2614,0
2,1665142500000,284.5,284.7,284.3,284.4,1084.894,1665142799999,308690.2988,728,650.581,185125.6882,0
3,1665142800000,284.4,284.5,284.3,284.4,283.491,1665143099999,80640.8539,339,202.762,57681.7428,0
4,1665143100000,284.5,284.6,284.1,284.3,1100.328,1665143399999,312893.2770,445,179.356,50999.4711,0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,1665440400000,272.5,272.8,272.2,272.7,779.529,1665440699999,212330.1694,653,575.644,156805.8658,0
996,1665440700000,272.7,272.8,272.5,272.7,590.122,1665440999999,160887.1464,419,431.080,117526.4057,0
997,1665441000000,272.7,273.0,272.5,272.9,687.945,1665441299999,187623.2880,471,258.336,70473.5376,0
998,1665441300000,272.9,272.9,272.2,272.4,963.143,1665441599999,262463.8768,610,274.375,74766.9277,0
999,1665441600000,272.4,272.5,272.1,272.1,328.950,1665441899999,89565.1642,275,44.199,12040.0181,0

In [3]:
url_binance_bnbusdt_1m = "https://api.binance.com/api/v3/klines?symbol=BNBUSDT&limit=1000&interval=1m"
df_binance_bnbusdt_1m = pd.read_json(url_binance_bnbusdt_1m)

df_binance_bnbusdt_1m.columns = [
    'open_time', 
    'open_price', 
    'high_price', 
    'low_price', 
    'close_price', 
    'volume', 
    'close_time', 
    'quote_asset_volume', 
    'number_of_trades', 
    'taker_buy_base_asset_volume', 
    'taker_buy_quote_asset_volume', 
    'unused'
]

df_binance_bnbusdt_1m

,open_time,open_price,high_price,low_price,close_price,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,unused
0,1665381780000,277.2,277.2,277.1,277.1,21.209,1665381839999,5877.6493,54,6.354,1761.3288,0
1,1665381840000,277.2,277.3,276.8,277.3,1551.793,1665381899999,429876.6422,338,173.210,47995.2356,0
2,1665381900000,277.2,277.3,277.2,277.2,13.108,1665381959999,3633.9123,39,3.747,1039.0431,0
3,1665381960000,277.2,277.4,277.2,277.4,16.884,1665382019999,4682.0543,42,15.220,4220.7353,0
4,1665382020000,277.3,277.6,277.3,277.5,91.222,1665382079999,25306.8027,81,79.409,22029.7235,0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,1665441480000,272.5,272.6,272.4,272.5,316.250,1665441539999,86176.0969,140,45.764,12471.0890,0
996,1665441540000,272.4,272.5,272.2,272.4,196.414,1665441599999,53494.1479,117,80.931,22040.6909,0
997,1665441600000,272.4,272.5,272.4,272.5,70.336,1665441659999,19160.9895,87,14.631,3986.9475,0
998,1665441660000,272.4,272.4,272.3,272.3,87.046,1665441719999,23706.6643,93,21.694,5909.4456,0
999,1665441720000,272.4,272.4,272.1,272.1,171.568,1665441779999,46697.5104,95,7.874,2143.6250,0

In [4]:
len(df_binance_bnbusdt_5m), len(df_binance_bnbusdt_1m)

(1000, 1000)

### Reading Rounds Data from Pancake Subgraph
ðŸ”— Source: https://api.thegraph.com/subgraphs/name/pancakeswap/prediction-v2

Method: `POST`

Query:

{ query: "{ rounds(first: 1000 where: {position_not: null} orderBy: epoch,orderDirection:desc) {
    id
    epoch
    position
    failed
    startAt
    startBlock
    startHash
    lockAt
    lockBlock
    lockHash
    lockPrice
    lockRoundId
    closeAt
    closeBlock
    closeHash
    closePrice
    closeRoundId
    totalBets
    totalAmount
    bullBets
    bullAmount
    bearBets
    bearAmount
    }
}", }

In [5]:
pancake_subgraph_url = 'https://api.thegraph.com/subgraphs/name/pancakeswap/prediction-v2'
pancake_rounds_query = '{"query": "{ rounds(first: 1000 where: {position_not: null} orderBy: epoch,orderDirection:desc) { id epoch position failed startAt startBlock startHash lockAt lockBlock lockHash lockPrice lockRoundId closeAt closeBlock closeHash closePrice closeRoundId totalBets totalAmount bullBets bullAmount bearBets bearAmount } }"}'

In [6]:
import requests
req_pancake_rounds = requests.post(url=pancake_subgraph_url, data=pancake_rounds_query)

In [7]:
req_pancake_rounds

In [8]:
json_pancake_rounds = req_pancake_rounds.json()

In [9]:
len(json_pancake_rounds["data"]["rounds"])

1000

In [10]:
df_pancake_rounds = pd.DataFrame.from_dict(json_pancake_rounds["data"]["rounds"])

In [11]:
df_pancake_rounds

,id,epoch,position,failed,startAt,startBlock,startHash,lockAt,lockBlock,lockHash,...,closeBlock,closeHash,closePrice,closeRoundId,totalBets,totalAmount,bullBets,bullAmount,bearBets,bearAmount
0,111093,111093,Bear,False,1665441046,22067035,0x339bb8f74f8ae8757ffd9b953c934d3abce2b1674004...,1665441355,22067138,0xc8d5adad4316935ff68e6943b519a769bee060874fd2...,...,22067239,0x436c788689b082163d0c8a865c5c2a100c56e319f617...,272.35467537,18446744073711485428,109,27.913629581845183327,57,18.642091599770950691,52,9.271537982074232636
1,111092,111092,Bull,False,1665440737,22066932,0xc965eb67d478279e548c36c3be2f6109a026af1bf967...,1665441046,22067035,0x339bb8f74f8ae8757ffd9b953c934d3abce2b1674004...,...,22067138,0xc8d5adad4316935ff68e6943b519a769bee060874fd2...,272.78432618,18446744073711485414,79,14.329594849609391301,35,8.470944648335804697,44,5.858650201273586604
2,111091,111091,Bull,False,1665440428,22066829,0x231911b16e34e17022eb74b84e53e91a3e831497c3e3...,1665440737,22066932,0xc965eb67d478279e548c36c3be2f6109a026af1bf967...,...,22067035,0x339bb8f74f8ae8757ffd9b953c934d3abce2b1674004...,272.62,18446744073711485401,100,27.359823739485588099,59,16.357992862020168995,41,11.001830877465419104
3,111090,111090,Bull,False,1665440119,22066726,0xc8c3b0ca067291ded85b1cd5f0518107a451014f96bb...,1665440428,22066829,0x231911b16e34e17022eb74b84e53e91a3e831497c3e3...,...,22066932,0xc965eb67d478279e548c36c3be2f6109a026af1bf967...,272.61000271,18446744073711485387,102,27.683997697599828445,58,22.726966885517459031,44,4.957030812082369414
4,111089,111089,Bull,False,1665439807,22066622,0x6a88ffb9d35fbdab0e3547233e2913840cd235ad1db2...,1665440119,22066726,0xc8c3b0ca067291ded85b1cd5f0518107a451014f96bb...,...,22066829,0x231911b16e34e17022eb74b84e53e91a3e831497c3e3...,272.2,18446744073711485371,100,19.644558094850182152,41,6.621708704580349946,59,13.022849390269832206
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,110098,110098,Bear,False,1665133296,21965610,0x10a4da62fe1dc224388b7dccbe74d461333aa319538d...,1665133606,21965706,0x9a4a0c1f0f5e05c28199cb1315a3e35911c647fd21eb...,...,21965784,0x8272afae49620601cb862115f2aece81d3482973f65b...,284.99720749,18446744073711471228,72,11.237555972704807631,32,5.498560334794193123,40,5.738995637910614508
996,110097,110097,Bull,False,1665132985,21965510,0x728a080d0895d40763be94f9c5efa30bd1be008bcbdf...,1665133296,21965610,0x10a4da62fe1dc224388b7dccbe74d461333aa319538d...,...,21965706,0x9a4a0c1f0f5e05c28199cb1315a3e35911c647fd21eb...,285.05577602,18446744073711471215,56,8.704738417694099111,24,4.838673675845713625,32,3.866064741848385486
997,110096,110096,Bull,False,1665132675,21965419,0xecdbc4f1d971d21e76646669d1f49a29a52ff1642f78...,1665132985,21965510,0x728a080d0895d40763be94f9c5efa30bd1be008bcbdf...,...,21965610,0x10a4da62fe1dc224388b7dccbe74d461333aa319538d...,285.03812972,18446744073711471202,57,9.415952222844263557,32,6.931258374896603743,25,2.484693847947659814
998,110095,110095,Bear,False,1665132366,21965319,0x37b1575f542c3944da5b480a7584c8a73554f17d89c1...,1665132675,21965419,0xecdbc4f1d971d21e76646669d1f49a29a52ff1642f78...,...,21965510,0x728a080d0895d40763be94f9c5efa30bd1be008bcbdf...,284.96,18446744073711471186,52,8.746426992175488776,21,5.152134013045671734,31,3.594292979129817042
999,110094,110094,Bear,False,1665132055,21965219,0x8672fc40dab96e41d4a279ec2bab34ea9bef8dc235c2...,1665132366,21965319,0x37b1575f542c3944da5b480a7584c8a73554f17d89c1...,...,21965419,0xecdbc4f1d971d21e76646669d1f49a29a52ff1642f78...,284.97,18446744073711471171,63,11.880022507291290955,25,4.117242472368927164,38,7.762780034922363791

In [29]:
# Create a key-column to join DataFrames
df_binance_bnbusdt_5m["timestamp_key"] = pd.to_datetime(df_binance_bnbusdt_5m["close_time"], unit='ms')
df_binance_bnbusdt_1m["timestamp_key"] = pd.to_datetime(df_binance_bnbusdt_1m["close_time"], unit='ms')
df_pancake_rounds["timestamp_key"] = pd.to_datetime(df_pancake_rounds["closeAt"], unit='s')

In [30]:
# Join Dataframes
df_joined = pd.merge_asof(df_binance_bnbusdt_5m, df_binance_bnbusdt_1m, on='timestamp_key',direction = 'nearest', tolerance=pd.Timedelta("5 min"))
df_joined

,open_time_x,open_price_x,high_price_x,low_price_x,close_price_x,volume_x,close_time_x,quote_asset_volume_x,number_of_trades_x,taker_buy_base_asset_volume_x,...,high_price_y,low_price_y,close_price_y,volume_y,close_time_y,quote_asset_volume_y,number_of_trades_y,taker_buy_base_asset_volume_y,taker_buy_quote_asset_volume_y,unused_y
0,1665141900000,284.5,284.5,284.3,284.4,371.447,1665142199999,105625.3143,318,173.538,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1665142200000,284.3,284.5,284.3,284.5,569.677,1665142499999,162046.5800,549,507.688,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1665142500000,284.5,284.7,284.3,284.4,1084.894,1665142799999,308690.2988,728,650.581,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1665142800000,284.4,284.5,284.3,284.4,283.491,1665143099999,80640.8539,339,202.762,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1665143100000,284.5,284.6,284.1,284.3,1100.328,1665143399999,312893.2770,445,179.356,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1665440400000,272.5,272.8,272.2,272.7,779.529,1665440699999,212330.1694,653,575.644,...,272.8,272.4,272.7,152.895,1.665441e+12,41675.8778,129.0,144.599,39414.9445,0.0
996,1665440700000,272.7,272.8,272.5,272.7,590.122,1665440999999,160887.1464,419,431.080,...,272.7,272.5,272.7,301.927,1.665441e+12,82310.0594,89.0,297.460,81092.4777,0.0
997,1665441000000,272.7,273.0,272.5,272.9,687.945,1665441299999,187623.2880,471,258.336,...,272.9,272.8,272.9,144.700,1.665441e+12,39482.5520,102.0,9.472,2584.9088,0.0
998,1665441300000,272.9,272.9,272.2,272.4,963.143,1665441599999,262463.8768,610,274.375,...,272.5,272.2,272.4,196.414,1.665442e+12,53494.1479,117.0,80.931,22040.6909,0.0
999,1665441600000,272.4,272.5,272.1,272.1,328.950,1665441899999,89565.1642,275,44.199,...,272.4,272.1,272.1,171.568,1.665442e+12,46697.5104,95.0,7.874,2143.6250,0.0